name: docker-build-push

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
      - name: Checkout the analysis repository
        uses: actions/checkout@v3
        with:
          repository: hsf-training/hsf-training-cms-analysis-snapshot
          path: analysis/skim
      - run: find .
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        continue-on-error: true
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ steps.docker_login.outcome == 'success' && github.ref_name == 'main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME || 'hsf-training' }}/hsf-training-minimal-github-actions-docker-build-push:latest
